### ISSUE TITLE
download text and content

### ISSUE THREAD

**Issue by timelyportfolio** [timelyportfolio/ebc_portal#1]
@scheng87 What would you like to say in the download section?  Should we use this space to describe the file formats instead or blend a discussion of formats with some text about proper usage and citation?

![image](https://user-images.githubusercontent.com/837910/39396438-bba66b36-4ab3-11e8-9c2d-7c24c12c6a06.png)

remembering that this is what the accepatance modal says

![image](https://user-images.githubusercontent.com/837910/39396446-e9f1bdb0-4ab3-11e8-911d-0bca2d338b40.png)

**Comment by scheng87** [comment]
Let's have the download text state -

"Below you will fill links to download custom, filtered datasets based on your chosen parameters. Data is available to download in two formats, 1) JSON (JavaScript Object Notation) and 2) CSV (comma-separated values). Both formats can be viewed and edited in a text editor. CSV files can be opened in Excel or another spreadsheet program. 

Please ensure that you properly cite any data you use from this study."

**Comment by timelyportfolio** [comment]
I think this is done.  @scheng87, let me know if we can close.
