### ISSUE TITLE
disclaimer added to beginning of visualizations

### ISSUE THREAD

**Issue by scheng87** [timelyportfolio/ebc_portal#14]
Could we add this somewhere on the visualizations page for each evidence map? 

"This map illustrates the quantity of evidence existing for specific linkages and geographies, but does not illustrate direction of impact nor quality of evidence."

**Comment by timelyportfolio** [comment]
@scheng87, 233b51e added the disclaimer that looks like this.  Let me know if that works.

![image](https://user-images.githubusercontent.com/837910/39734771-43dd6f54-523e-11e8-9439-222910cfe2d1.png)

**Comment by scheng87** [comment]
Perfect!
