### ISSUE TITLE
deploy site on netlify

### ISSUE THREAD

**Issue by timelyportfolio** [timelyportfolio/ebc_portal#15]
@scheng87, will we buy a custom domain for this?  I'll start working on a netlify deploy, and then we can add the custom domain easily.

**Comment by scheng87** [comment]
We already have a custom domain for this - www.natureandpeopleevidence.org - i'll have NCEAS transfer it to me ... ?

**Comment by scheng87** [comment]
How do I do that ... do I have to sign up for a netlify account?

**Comment by timelyportfolio** [comment]
@scheng87 given the time crunch, I will plan to transfer and deploy.  After release, we can work together to move to you.
