### ISSUE TITLE
styling

### ISSUE THREAD

**Issue by scheng87** [timelyportfolio/ebc_portal#16]
Fonts that were used for headers and dropdown menus was: Myriad Pro Condensed (e.g. About, Contact, Understand, Explore, Updates and content within, along with headers in text)

Body text was Helvetica Neue

Evidence for Nature and People Data Portal was Myriad Pro Regular

Can we set these?

**Comment by scheng87** [comment]
Second styling - can we make the black boxes on the front page a bit bigger so there is more margin around the text? see mockup attached 
![image](https://user-images.githubusercontent.com/16600208/39641039-b59fad92-4f81-11e8-9bbc-e4fb80f97c97.png)

![image](https://user-images.githubusercontent.com/16600208/39641046-bb703b24-4f81-11e8-9e4a-5dc3206e46db.png)

**Comment by timelyportfolio** [comment]
@scheng87 where do I get Myriad Pro?  Is it an Apple Font?  If Apple, what would you like as a substitute on non-Apple?  Thanks.

**Comment by timelyportfolio** [comment]
@scheng87 I found this http://joelcrawfordsmith.com/closest-font/font/myriad-pro as an option.

**Comment by scheng87** [comment]
Sure that looks fine! Does it have the condensed option for the titles? If not, we can use highway gothic condensed

Thanks!

**Comment by timelyportfolio** [comment]
@scheng87 Yes there is a Narrow option.  I will have it deployed in just a bit so you can review.  Thanks!

**Comment by scheng87** [comment]
Could we change the font to highway gothic for these headers?
![image](https://user-images.githubusercontent.com/16600208/39667058-c0de82aa-5062-11e8-9563-af4bb9f3f202.png)

**Comment by timelyportfolio** [comment]
Highway Gothic is not widely available.  I see it here http://overpassfont.org/ but don't have a lot of experience with it.  If we deem it "worth the load" and feel comfortable with this CDN, I'd like to use for more than just the couple of headers.

**Comment by scheng87** [comment]
Sorry i meant whatever you used for the dropdown menus!

**Comment by timelyportfolio** [comment]
@scheng87, no problem.  Regular or Narrow/Condensed?  I did regular for now if you would like to see how it looks.

**Comment by scheng87** [comment]
Regular looks fine! I think I can always fiddle them later if I feel restless :-)
