### ISSUE TITLE
styling - filters

### ISSUE THREAD

**Issue by scheng87** [timelyportfolio/ebc_portal#17]
could we add a box around the filters? Or a solid background to make it easier to see?

sort of like this:

![image](https://user-images.githubusercontent.com/16600208/39641552-784354ec-4f83-11e8-8fbb-2af357bb18d9.png)

**Comment by scheng87** [comment]
Or this:

![image](https://user-images.githubusercontent.com/16600208/39641591-a1fc6792-4f83-11e8-826a-32ac63479113.png)

**Comment by timelyportfolio** [comment]
@scheng87 I added a background, but I am still not happy with how it looks.  Please let me know if you have any ideas.  I also changed the blue to match the cards.

![image](https://user-images.githubusercontent.com/837910/39663599-a1abf43e-503b-11e8-9ee9-fbcaae9ecf3c.png)

**Comment by scheng87** [comment]
How about like this? 
![image](https://user-images.githubusercontent.com/16600208/39667320-1627adea-5068-11e8-8d36-38da0a4a9229.png)

**Comment by timelyportfolio** [comment]
@scheng87 I really appreciate the design ideas.  At this point, I am so focused on the code that I am really struggling + I think you just are better at it :)

If you are doing this in `HTML/CSS`, feel free to attach bits and pieces to these issues.

**Comment by timelyportfolio** [comment]
@scheng87 I implemented but made some small changes choosing the bluish background for the title and keeping gray for filters and navbar.  Happy to change though if you disagree.

**Comment by scheng87** [comment]
Looks good! Maybe just make the filters white (keep header that says filter gray) and have faint gray lines separating each filter category? (like the badges) and then maybe increase the margin around the font or decrease the font size so there is more background?

And then for data explorer title - maybe bold the text for data explorer: and then keep the rest normal. then expand and add the disclaimer from the other issue (i think issue #13) below that in small font and italics?

**Comment by timelyportfolio** [comment]
@scheng87, can we close this?  Unfortunately I don't see an easy way to only add gray lines to separate the parent levels.

**Comment by scheng87** [comment]
That’s fine! Yes let’s close
