### ISSUE TITLE
styling - cards

### ISSUE THREAD

**Issue by timelyportfolio** [timelyportfolio/ebc_portal#18]
@scheng87 I don't feel like the cards approach works all that well with the new design, so I am trying to think of other methods to convey the counts.  

![image](https://user-images.githubusercontent.com/837910/39664943-7538261e-5051-11e8-8883-92be83970fdf.png)

Some thoughts are to reduce the size or use badges within the navbar ([example](https://getbootstrap.com/docs/4.0/components/list-group/#with-badges)).

**Comment by scheng87** [comment]
Agreed, I like the badges approach! Maybe put them above the filters so it ends up being a side panel? Kind of like that ... class pass example I sent yesterday?

**Comment by timelyportfolio** [comment]
ref https://github.com/timelyportfolio/ebc_portal/issues/17#issuecomment-386832612

**Comment by timelyportfolio** [comment]
@scheng87, can we close this one?

**Comment by scheng87** [comment]
Yes!
