### ISSUE TITLE
content for contact page

### ISSUE THREAD

**Issue by timelyportfolio** [timelyportfolio/ebc_portal#2]
@scheng87, please let me know what content you would like in the contact page 

![image](https://user-images.githubusercontent.com/837910/39396495-ce1f5da8-4ab4-11e8-84fd-71577a64b1c4.png)

In the old version, we had http://natureandpeopleevidence.org/ebc-dataportal/.

**Comment by scheng87** [comment]
"For more information about the Evidence for Nature and People Data Portal and/or the Science for Nature and People Partnership (SNAPP) Evidence Based Conservation Working Group, please contact Samantha Cheng (samantha.cheng@asu.edu) or Madeleine McKinnon (madeleinem@vulcan.com).

If you are interested in submitting evidence relevant to the Data Portal, please contact Samantha Cheng (samantha.cheng@asu.edu)

For more information about the Forests and Poverty Evidence Map and/or the Program on Forests, please visit http://www.profor.info or contact Sofia Ahlroth (sahlroth@worldbank.org) or Emilie Perge (eperge@worldbank.org)."

**Comment by timelyportfolio** [comment]
@scheng87 please check to see if this is ok.  Thanks.

**Comment by timelyportfolio** [comment]
closing; feel free to reopen
