### ISSUE TITLE
explanatory text to add to each vis type

### ISSUE THREAD

**Issue by scheng87** [timelyportfolio/ebc_portal#20]
How much lift would be it to add text to each vis type? Is this something I can do?

E.g. For the countries --
"This shows the number of unique articles that document a link between an intervention and an outcome for each country studied."

For heatmap --
"This shows the number of unique articles that document specific intersections of an intervention and an outcome. Because articles can study more than one intervention or outcome type, articles may occur in more than linkage cell. Darker colors indicate greater volume of articles."

etc...

**Comment by timelyportfolio** [comment]
@scheng87 Not too bad, but I worry that a lot of little is going to really add up.  You can do anything.  The only problem though is that you will need a development environment to see the changes in real-time.  Do you have node.js?

**Comment by scheng87** [comment]
I believe I do...

I’d like to have the text so as to avoid any misinterpretation of the vis!

**Comment by scheng87** [comment]
Do you think you have time to add the explanatory text?

**Comment by timelyportfolio** [comment]
@scheng87 if you provide the text I can implement on Monday.

**Comment by scheng87** [comment]
Hi Kent

Sorry for delay!

For the countries --
"This shows the number of unique articles that document a link between an intervention and an outcome for each country studied."

For heatmap --
"This shows the number of unique articles that document specific intersections of an intervention and an outcome. Because articles can study more than one intervention or outcome type, articles may occur in more than linkage cell. Darker colors indicate greater volume of articles. This map shows quantity of evidence but does not illustrate direction nor magnitude of impact."

For intervention by region -- 
"This shows the number of unique articles that examine different intervention types in different geographic regions. Because articles can study more than one intervention and region, articles may occur in more than graph."

For habitat by region -- 
"This shows the number of unique articles that examine different habitat types in different geographic regions. Because articles can study more than one habitat and region, articles may occur in more than graph."

For study type by comparator -- 
"This graph shows the types of comparators used in different study designs over the evidence base. Because articles can use more than one type of comparator, they can appear more than once within a single graph panel."

For intervention combination -- 
"Interventions are often complex and include actions that fall into multiple intervention categories. This graph shows which intervention types commonly co-occur within a studied program or comparative study."

**Comment by timelyportfolio** [comment]
@scheng87 I added the details to each profor vis https://www.natureandpeopleevidence.org/index_real.html#/explore/profor/charts.  I liked better when the details remained with title and did not hide on collapse.  Do you agree?

If you like these, should I use the same where appropriate for human well-being?  Thanks.

**Comment by scheng87** [comment]
Yes looks great! And yes please add to human well being . Thank you!

**Comment by timelyportfolio** [comment]
@scheng87 I added to human well-being.  Please let me know if we can close this one.  Thanks!

**Comment by scheng87** [comment]
I’m in the car and can’t check but I’m sure it’s fine! Thank you!
