### ISSUE TITLE
content for portal & tool

### ISSUE THREAD

**Issue by timelyportfolio** [timelyportfolio/ebc_portal#3]
@scheng87, also we will need content for 

![image](https://user-images.githubusercontent.com/837910/39396508-148e5d66-4ab5-11e8-9d4d-b31b619b3022.png)

**Comment by scheng87** [comment]
ABOUT THE PORTAL
This is an open access online data portal and visualization designed to help users explore the existing evidence on linkages between nature and people. The evidence collated in this tool is designed to help conservation and development policymakers, practitioners, and researchers identify relevant information for decision-making. To date, the portal hosts 3 evidence maps containing nearly 1,500 peer-reviewed articles, unpublished reports, and theses in the evidence base. You can access each of these evidence maps through the EXPLORE menu above.

The portal provides a gateway to filter and visualize patterns in these evidence maps and download subsets of the data and relevant bibliographies. Most of the generated plots on this page are made using Plotly, therefore you can use the controls in the upper right corner of each graph to toggle and adjust the image, as well as download them. Any data, graphs, or summaries downloaded from this tool must be cited appropriately. 

Below, you will find an instructional video about how to use the tool as well as a set of FAQs. 

HOW TO USE THE PORTAL
Short video tutorial on using the EBC data portal (video link)

HOW THIS PORTAL WAS BUILT
This portal was built by Kenton Russell using [input from KENT].The source code for this portal is available at [github link] and licensed under a [license type].

FEEDBACK
As this tool is designed to help users find and explore usable data, feedback would be very much appreciated on functionality and utility. Please see the CONTACT tab to fill out a feedback form or you can directly email the postdoctoral fellow, Samantha Cheng at cheng@nceas.ucsb.edu .

For any questions or comments, please contact Samantha Cheng (samantha.cheng@asu.edu).

ACKNOWLEDGMENTS
The concept for the Evidence for Nature and People Data Portal was conceived by the Evidence-Based Conservation Working Group. This portal is supported by the Science for Nature and People Partnership consisting of the National Center for Ecological Analysis and Synthesis (NCEAS), The Nature Conservancy, and the Wildlife Conservation Society. Without the technical expertise and computing support from the scientific computing team at NCEAS (Julien Brun, Nick Outin, Ian McCullough, Sarah McCutcheon, Justin Kroes, Mark Schildhauer, & Lauren Walker) this tool would not have been possible. This current version of the tool is built by Kenton Russell. This tool was developed and piloted with a number of potential end-users including scientists, researchers, and practitioners from multiple academic, conservation, and development institutions and agencies.

**Comment by scheng87** [comment]
Just following up on this one! - there are brackets in there for input from you re: the packages, etc... used

**Comment by scheng87** [comment]
ABOUT THE PORTAL
This is an open access online data portal and visualization designed to help users explore the existing evidence on linkages between nature and people. The evidence collated in this tool is designed to help conservation and development policymakers, practitioners, and researchers identify relevant information for decision-making. To date, the portal hosts 3 evidence maps containing nearly 1,500 peer-reviewed articles, unpublished reports, and theses in the evidence base. You can access each of these evidence maps through the EXPLORE menu above.

The portal provides a gateway to filter and visualize patterns in these evidence maps and download subsets of the data and relevant bibliographies. Most of the generated plots on this page are made using Plotly, therefore you can use the controls in the upper right corner of each graph to toggle and adjust the image, as well as download them. Any data, graphs, or summaries downloaded from this tool must be cited appropriately.

Below, you will find an instructional video about how to use the tool as well as a set of FAQs.

HOW TO USE THE PORTAL
Short video tutorial on using the EBC data portal (video link)

HOW THIS PORTAL WAS BUILT
This portal was built by Kenton Russell using [input from KENT].The source code for this portal is available at [github link] and licensed under a [license type].

h4(div(strong("FAQs"),style="color:#006699"),align="center"),
                        br(),
                        h5(div(strong("I am looking for a specific action or outcome, how do I find out what category that falls into?"))),
                        p("The glossary is the best place to figure out what types of actions or outcomes fall into which categories. Since we used either standardized typologies or synthesized frameworks, the definitions stem from those references. Below the definition, you find examples of what types of actions are included. The glossary can be found at the bottom of every page. Click the 'Show/Hide glossary' button to display the panel. You can also find the glossary in the ABOUT section, and then navigating to GLOSSARY."),
                        br(),
                        h5(div(strong("Where do I filter data and explore it? Why are there so many different options?"))),
                        p("This site is constantly in development and we are refining it to make searching for and exploring data as functional and intuitive as possible. As well, while Shiny is a fantastic method for visualizing data, it can be difficult to incorporate multiple elements that it is not designed for. Hence, there are different tabs for exploring data. We encourage you to watch the how-to video on how to explore, filter, and download data."),
                        p("In general, options for exploration are located in the ",span(strong("EXPLORE"),style="color:#006666")," section. Within this section, in the ",span(strong("VISUALIZATION"),style="color:#006666")," tab, you can filter data from an individual evidence synthesis by geography, intervention/action type, outcome type, study design, and habitat. This data is displayed in a number of visualizations displaying the resulting number of unique articles. Here you can view summaries of different variables, explore the full data, and visualize spatially on both choropleth and interactive maps. You can also view the data table behind this map by clicking on the ",span(strong("TABLE"),style="color:#006666")," tab."),
                        br(),
                        h5(div(strong("Are there other efforts to expand from this evidence map or on other topics?"))),
                        p("You can read more about ongoing work to build this evidence base and conduct in-depth syntheses on some of these linkages in the",span(strong("RESEARCH"),style="color:#006666"), "tab"),

FEEDBACK
As this tool is designed to help users find and explore usable data, feedback would be very much appreciated on functionality and utility. Please see the CONTACT tab to fill out a feedback form or you can directly email the postdoctoral fellow, Samantha Cheng at cheng@nceas.ucsb.edu .

For any questions or comments, please contact Samantha Cheng (samantha.cheng@asu.edu).

ACKNOWLEDGMENTS
The concept for the Evidence for Nature and People Data Portal was conceived by the Evidence-Based Conservation Working Group. This portal is supported by the Science for Nature and People Partnership consisting of the National Center for Ecological Analysis and Synthesis (NCEAS), The Nature Conservancy, and the Wildlife Conservation Society. Without the technical expertise and computing support from the scientific computing team at NCEAS (Julien Brun, Nick Outin, Ian McCullough, Sarah McCutcheon, Justin Kroes, Mark Schildhauer, & Lauren Walker) this tool would not have been possible. This current version of the tool is built by Kenton Russell. This tool was developed and piloted with a number of potential end-users including scientists, researchers, and practitioners from multiple academic, conservation, and development institutions and agencies.

**Comment by timelyportfolio** [comment]
@scheng87 I began building this section. http://www.natureandpeopleevidence.org/index_real.html#/about/tool.  I noticed some of the text is outdated with the new site.  I will try to revise so that it is current.

Also, do we want to style such that alternating sections are white and dark?

**Comment by scheng87** [comment]
Thanks Kent!

Yes I think that would look nice? It should go about, how it was built, how to use it, FAQs, feedback, acknowledgments

**Comment by timelyportfolio** [comment]
ok, I alternated but combined first two as white since the second section is so small.  I also reworded just a little bit to fit the new site.

**Comment by timelyportfolio** [comment]
Going to close, but happy to reopen if we need improvement here.
