### ISSUE TITLE
duplicates in comparators for conservation/human well-being

### ISSUE THREAD

**Issue by scheng87** [timelyportfolio/ebc_portal#30]
Sorry, just noticed this - but the comparators in conservation/human well-being have lots of duplicates i think due to difference in syntax. How can i best facilitate that fix? Is it by fixing the original dataset and sending you that? If so, let me know which file and I can get on that ASAP

**Comment by timelyportfolio** [comment]
@scheng87, fixing this will be delicate.  I worry that we won't have adequate time for testing.  How much time do we have?

**Comment by scheng87** [comment]
Hmm I guess June 18? But if that’s an issue, we can leave it and I can fiddle later?

**Comment by timelyportfolio** [comment]
@scheng87 I believe this is now resolved.
