### ISSUE TITLE
extra column included in data download

### ISSUE THREAD

**Issue by scheng87** [timelyportfolio/ebc_portal#33]
How easy would it be to eliminate an entire column from the data download? Realized that direction of outcome is still in there (I never removed it from the original dataset that feeds it) - is it better to remove it from the original data file or remove it from what is downloaded? It's columns called "Outcome.direction" and  "Outcome.direction_notes"

**Comment by timelyportfolio** [comment]
@scheng87, probably easiest to remove from the `csv`, but I guess I will also need to remove from the `json` as well.  I will try to do it when I fix the duplicates comparators.  MIght be a c.ouple of days, since I will need to fully test.

**Comment by scheng87** [comment]
Thanks! If it’s more than a quick fix, leave it for now!!

**Comment by timelyportfolio** [comment]
@scheng87, this should now be complete.
