### ISSUE TITLE
color scheme for map and heatmap

### ISSUE THREAD

**Issue by timelyportfolio** [timelyportfolio/ebc_portal#6]
"Colours – switch around, so that the largest number is the darkest blue and the smallest number is yellow"

After talking to @scheng87, we agreed that reversing might confuse a user who is familiar with the normal order of `viridis`.  We talked about another color scheme.  Here are the options https://vega.github.io/vega/docs/schemes/#sequential-single-hue-schemes.  @scheng87, please let me know which you think is best or ask Sofia/team.  Thanks.

**Comment by scheng87** [comment]
Let's use blue green!

**Comment by timelyportfolio** [comment]
@scheng87, will you check to see how you like `bluegreen`?

**Comment by timelyportfolio** [comment]
@scheng87 I will close; we can reopen if someone wants to change to a different color scheme.
